### ISSUE TITLE
Cannot be enabled due to issues in required dependencies

### ISSUE THREAD

**Issue by HeardMatthew** [mysurvive/pf2e-thaum-vuln#105]
Hi, apologies if this is the wrong place to seek support. I am using VTT v11 build 315 in Pathfinder 2e 5.14.4. I am unable to activate the module as it shows a "Cannot be enabled due to issues in required dependencies" when I mouse over the module. I have a small handful of other modules active, but the issue persists in a different world which has no other modules loaded. 

Any recommendations on how to fix? Thanks!

**Comment by mysurvive** [comment]
Socketlib is the only module dependency

**Comment by mysurvive** [comment]
This page should also help! https://github.com/mysurvive/pf2e-thaum-vuln/wiki/Getting-Started

**Comment by zipperguy** [comment]
I'm still having this exact issue with version 12 stable build 331. I have a few other modules that rely on socketlib that are able to be enabled but I continue to be unable to select this module despite my troubleshooting. I have tried reinstalling socketlib, disabling every other module, and restarting Foundry but nothing seems to work.

**Comment by mysurvive** [comment]
This issue is over a year old and was resolved by enabling socketlib.

The module now relies on libwrapper as well, make sure it is enabled and turned on as well.

If you continue having an issue, open a _new issue_ please.
