### ISSUE TITLE
Compatibility Issue version 0.15.4 and upwards

### ISSUE THREAD

**Issue by Broken-One-tr** [mysurvive/pf2e-thaum-vuln#166]
If I understand correctly, versions 0.15.x should be compatible with Foundry 11 and the working PF2E system available for this version. However, when I update to version 0.15.4 or above, it remains compatible with Foundry 11 but depends on a PF2E system that is only available with Foundry 12. This seems to require a quick fix.

**Comment by mysurvive** [comment]
This is the manifest for 0.15.4
![image](https://github.com/user-attachments/assets/29bc5c58-37de-435a-a08d-16d17a709f85)
It is set correctly. You're probably trying to auto update, but you have to install from the manifest URL.
