### ISSUE TITLE
Sipping Chalice duration

### ISSUE THREAD

**Issue by cykotek** [mysurvive/pf2e-thaum-vuln#169]
Using the "Sip Chalice" macro applies temporary hit points and an effect to the target.  However, the temporary hit points and effect expire when the end of the round is reached, i.e., when the last actor on the encounter tracker hits "End Turn" and the initiative returns to the top of the initiative for a new round.

**Comment by mysurvive** [comment]
It sure does, good catch. I'll have a fix for it.
