### ISSUE TITLE
newly added Implements are undefined

### ISSUE THREAD

**Issue by lassesos** [mysurvive/pf2e-thaum-vuln#182]
When managing implements and confirming changes the implements does not work. when you hover over the implement icon it says "undefined implement" instead of first/secound implement. module version is 0.16.7
![implementIssue](https://github.com/user-attachments/assets/52a6980f-cbc8-4a0f-a3aa-387ffc357aba)

**Comment by mysurvive** [comment]
I think that's just a tooltip error, does the implement work otherwise?

**Comment by lassesos** [comment]
no it does not work in my or my friends friends game. we noticed it with the amulet implementation first. it was working initially on an earlier created thaumaturge however after clearing the implements and re-adding that character broke too.

**Comment by mysurvive** [comment]
I just updated my system, cleared implements, re-added implements, and it's still working for me
![image](https://github.com/user-attachments/assets/23909e10-ff83-4fdc-95de-d9c3a23ef406)

You might need to try disabling some modules.

**Comment by GezmeRR** [comment]
Hello, i am having the same issue, i loaded up a world only with kingmaker and your module, and the issue is still there
The PF2e system haves gotten a few updates lately, perhaps thats the issue?
![2024-11-26 12_36_17-Foundry Virtual Tabletop](https://github.com/user-attachments/assets/cbb11bc3-39d7-4173-b9e8-77a65c07378e)

**Comment by GezmeRR** [comment]
![image](https://github.com/user-attachments/assets/63476a7c-68fa-4986-b0d8-353319d7d57c)
Good news! Even in our main campaing it seems to be working now!
