### ISSUE TITLE
Can't manage 2nd implemente - weapon

### ISSUE THREAD

**Issue by Turqueso** [mysurvive/pf2e-thaum-vuln#40]
I'm adding a second implement - weapon but when I try to manage and add any weapon in the inventory, this is no saved. I'm getting this error in console:

```
Uncaught (in promise) TypeError: impl is null
[Detected 1 package: pf2e-thaum-vuln]
    deleteImpEffect helpers.js:25
```

Pf2e 5.1.2
Foundry 11 (305)

**Comment by mysurvive** [comment]
Try this:

1.  Press f12
2. Select the thaumaturge token
3. in the console window, type `_token.actor.unsetFlag("pf2e-thaum-vuln","selectedImplements")`

You will need to re-add your first implement again. Let me know if that helps. If not, please let me know what weapon you're trying to apply, if you've altered it at all, if it's in the compendium or in the items tab, etc. Just as much information as possible.

**Comment by Turqueso** [comment]
that helped, thank you!
