### ISSUE TITLE
Module Error on Load

### ISSUE THREAD

**Issue by Aeristoka** [mysurvive/pf2e-thaum-vuln#44]
Occurs immediately on loading any scene with this module enabled.

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/7988297/b53add2b-cd84-452e-ac01-9d4e63243cd0)

**Comment by mysurvive** [comment]
This is from an old chat card where the flag doesn't exist anymore and the module is picking it up. Are you actually having an issue or just don't like the red?

**Comment by Aeristoka** [comment]
Just saw the issue pop and didn't know if it was causing issues at the time (cleared most of the lag and such by disabling all the beautiful animation modules).

Thanks for the explanation!

**Comment by mysurvive** [comment]
Sure thing! I'll see if I can get rid of the red in this next release.

**Comment by mysurvive** [comment]
I haven't noticed this in any of my games, so I believe it's fixed now! :)
