### ISSUE TITLE
Manage Implement gives error

### ISSUE THREAD

**Issue by Fyrexian** [mysurvive/pf2e-thaum-vuln#46]
Foundry: 11.305
PF2e: 5.1.2

When I click "manage implements" it doesn't do anything and gives this error:
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/47077661/d63f3e28-d3d5-45a4-9781-3d8593255f7f)

**Comment by mysurvive** [comment]
Send a screenshot of your feats tab

**Comment by mysurvive** [comment]
Any scenario where Manage Implements would error out and break should have some form of error checking now. If you continue having issues after updating, let me know.

**Comment by Fyrexian** [comment]
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/47077661/3585adaa-c047-4c2d-bcce-90518c15c437)

Still having this issue

**Comment by Fyrexian** [comment]
Nevermind, deleting all feats and giving them again fixes it
