### ISSUE TITLE
Manage implement breaks when exporting/importing between world

### ISSUE THREAD

**Issue by uniwars** [mysurvive/pf2e-thaum-vuln#48]
Hi, when exporting a PC from a world to another the manage implement menu breaks. In one case the button did not work with this error :

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/65986545/85ee09c6-d2cd-4a4d-9da5-c4043bd80591)

and in another case the actor which had already set implement in world 1 is imported with those implements marked as such in the inventory but when opening the "manage implements" menu it looks like there was no implements and it's impossible to set new ones :

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/65986545/f7686947-6883-4567-afe5-0527bdbb199e)

and when trying to set new ones :

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/65986545/cbf787a6-e4a0-465c-b7d6-cd92e8a083a7)

**Comment by mysurvive** [comment]
Manage Implements looks at the uuid of the item. When you export/import, the uuids change. You will need to run 
`_token.actor.unsetFlag("pf2e-thaum-vuln","selectedImplements")` with the token selected to clear the selected implements. I will add a button to clear the implements in a future release.

**Comment by mysurvive** [comment]
The latest release should error this out more gracefully, but the previous statement still remains about changing uuids.
