### ISSUE TITLE
Mortal weakness not added to target

### ISSUE THREAD

**Issue by uniwars** [mysurvive/pf2e-thaum-vuln#5]
Hi, I used the macro on Chafkhem from Abomination Vault bestiary and choosed the Mortal Weakness after a success but the effect was only added on me and not the target, I tried twice.

**Comment by mysurvive** [comment]
Personal antithesis and mortal weakness are both working for me on that token. Do you have errors in the console log?

**Comment by uniwars** [comment]
I did some tests, on a new droped monster token it works, but on the token that was already on the scene it doesn't
the aura of the monster doesn't work as well with the one already on the scene (using the official AV module)

I think I need to import again because I had another issue with the macro, I got a monster ( Seugathi Guard) with "undefined resistance except undefined" but it was resistance 5 to bludgeoing

**Comment by uniwars** [comment]
I tried with a new import of AV on another world and it doesn't work neither :
![image](https://user-images.githubusercontent.com/65986545/221408681-050c9559-35fb-494c-9ffc-827d59f27fd6.png)

**Comment by uniwars** [comment]
I have no other premium content to test if it's the same for all

**Comment by mysurvive** [comment]
The Seugathi Guard was working fine for me, but I found the Chafkhem bug and it's fixed in the latest release.
