### ISSUE TITLE
Changing HP, Stamina or Resolve on the sheet brings up the manage implement popout when using a lantern implement

### ISSUE THREAD

**Issue by Peach774** [mysurvive/pf2e-thaum-vuln#53]
This happens whether the implement is stowed, worn, or held.

**Comment by Peach774** [comment]
Any update on fixing this? its really obnoxious.

**Comment by mysurvive** [comment]
If you don't press enter and instead click anywhere else outside of the HP box, the health will update without opening the manage implements screen. This is the best suggestion have until I have a chance to take a look at it. I'm sorry that this is causing you grief.

**Comment by mysurvive** [comment]
Fixed in latest
