### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by dharkus5000** [mysurvive/pf2e-thaum-vuln#6]
it tells the player the weakness amount on success, regardless of whether the mystify option is enabled, which they should only get on a crit, then on a crit with mystify enabled, the amount is hidden
also it only turns off the weakness when another PC specifically strikes, so spells and auto-dmg like combat grab still applies weakness as it's still present on the enemy
also with a test demon (they all have cold iron and good weakness), it only ever told the player about the good weakness, after like 15+ rolls of success, when it's supposed to tell them 1 of the weaknesses when it has multiple of the same value, this should probably be a random one rather than always the same one regardless of how many successes you got? maybe even long which are known, and tell the other?

**Comment by mysurvive** [comment]
I fixed (I hope) most of the more pressing issues you brought up in the latest release. The EV Effects should no longer carry over to other characters when they make spell strikes (and also persistent damage should work properly too) and the mystification should be correct now.
I'll have to work on the randomization of the weakness shown some other time, but I believe that solves the most important issues.

**Comment by mysurvive** [comment]
OK the highest weakness is now randomized. It doesn't remember what you've already learned, but it _does_ randomize it! 5c326c749d81b841de9187ae6885f6d36e1db594
