### ISSUE TITLE
Game lags, fps drops, when Personal Antithesis or Mortal Weakness effects get put on or taken off tokens.

### ISSUE THREAD

**Issue by Shakespar** [mysurvive/pf2e-thaum-vuln#60]
Just thought I would leave an issue here per our discussion on discord a week and a half ago.  feel free to @shakespar on the pf2e foundry discord if you need any information from me diagnosing the problem.  Thanks for all you do.

**Comment by mysurvive** [comment]
I have a maybe semi fix sitting in a branch for this, but I don't know how much it will help. I haven't seen anyone else mention the severity of issue you're having and on my  AWS and Oracle hosted games it's pretty smooth.

**Comment by Yonzoo1105** [comment]
Ditto to this. Experience the same thing when applying/removing the effects.

**Comment by LeKopic** [comment]
Same here.

**Comment by mysurvive** [comment]
It might get a little better with 5e96b33 
If not, there's not much else I can do until there are some system features that get put in

**Comment by LeKopic** [comment]
Hey, sorry to barge into the closed issue, but I think I might have a clue. 

I have discovered that PF2e system (or, maybe, Foundry in general) has an issue with assigning conditions to linked PCs, if there are duplicates or multiple tokens placed on many maps. In my new game this module behaves a-ok, but in the older one - it is really laggy.

After deleting each thaum's token on all scenes except the current one it works great without (almost) any lag.
