### ISSUE TITLE
[Bug] Implement Overwriting Base REs

### ISSUE THREAD

**Issue by Crowguard** [mysurvive/pf2e-thaum-vuln#62]
When selecting a weapon with already existing rules elements, such as the Smoking Sword from Beginner Box, the implement's REs seem to be clearing them out.

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/99844555/4cfbe7f0-3c71-4bc9-9766-80281bb1ecbd)

Foundry 11.308
PF2 5.5.3
PF2 EV 0.11.10
FTC ✔️

**Comment by mysurvive** [comment]
That's a big oopsie. Give me a few.

**Comment by Crowguard** [comment]
Doesn't seem to be applying them to any weapons for me now; Smoking Sword is shown in the video, but I tested with the normal +1 striking longsword as well.

https://github.com/mysurvive/pf2e-thaum-vuln/assets/99844555/e9ad03d8-d9f1-4100-ba29-c8529ce600d0

Same settings as above, except EV 0.12.0

**Comment by mysurvive** [comment]
Ok good that was the intent. I rewrote that part of the code and it became a bit of pointless code so it got the axe
