### ISSUE TITLE
Fling Magic missing item?

### ISSUE THREAD

**Issue by Queranil** [mysurvive/pf2e-thaum-vuln#65]
Hi, I'm probably overlooking something, but I created a new character for one of my players. When trying to execute the Fling Magic macro (from wand implement) I keep getting the message that the actor is missing an item [ID KPmj8dZpcuD1EG
f]. I tried to manage implement and selecting an item as the wand implement, holding it in a hand, assigning the actor to a player. All no effect. What am I doing wrong?

**Comment by mysurvive** [comment]
That's not my error, I don't have the wand implement implemented into the module yet.
