### ISSUE TITLE
[Bug] Breached Defenses

### ISSUE THREAD

**Issue by Crowguard** [mysurvive/pf2e-thaum-vuln#66]
When selecting this option via the macro, it results in an error and no effects being applied.

https://github.com/mysurvive/pf2e-thaum-vuln/assets/99844555/579ab078-0f87-480c-bd75-3be85bc9b4dd

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/99844555/439b3385-e2c3-4023-a864-ac48ae0456ec)

Foundry 11.311
PF2 5.6.1
EV 0.12.0

**Comment by mysurvive** [comment]
looks like the config properties got changed around, I'm working on it. Thanks for reporting! :)

**Comment by mysurvive** [comment]
might be fixed with 5c5f275 Let me know if any issues crop up and I can fix them probably pretty quickly.
