### ISSUE TITLE
[Bug] Cursed Effigy using the wrong predicate

### ISSUE THREAD

**Issue by Faulchu** [mysurvive/pf2e-thaum-vuln#68]
Cursed Effigy is using "saving-throw" as a predicate, where it should be using "check:type:saving-throw". May even be redundant, but I don't have the know-how to fully check.

![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/108874944/8de23cbe-23a1-4a4b-99dd-c61536385bce)
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/108874944/45cc5097-2731-4f4f-b7d3-5217ca762e77)

**Comment by mysurvive** [comment]
This will be fixed in the next update, which will likely be after the next system release
