### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Stotorm** [mysurvive/pf2e-thaum-vuln#7]
Hello, do you allow me to try to work on a translation for french user ? 
Using this website would help a lot, this allows the projects that register on it to generate language files in all languages and makes it easier to maintain them as every change appears allowing the translators to process in real time or almost

https://weblate.foundryvtt-hub.com/

**Comment by sakusenerio** [comment]
Chinese users have the same request as well!

**Comment by mysurvive** [comment]
I put in the request to put the project on webplate. I'm just waiting for the approval. I don't know how localization works, so please let me know if I did something wrong.

**Comment by mysurvive** [comment]
The project is on weblate now
