### ISSUE TITLE
[Request] Allow custom Implements.

### ISSUE THREAD

**Issue by AporieTM** [mysurvive/pf2e-thaum-vuln#72]
With the 5.8. update to the pf2e system there was a native ability to add homebrew implements integrated based on the tag system.

"Allow Thaumaturge Implements to accept homebrew"

While not pressing, it sure would be nice to make custom implements work with the module.

Big Thanks for your work!

**Comment by mysurvive** [comment]
Sorry this is taking so long, I'm pecking away at it slowly. It kind of requires a little bit of a refactor so it might be a bit before I get this wrapped up.

**Comment by AporieTM** [comment]
It simply being on the radar is worth plenty already.

**Comment by mysurvive** [comment]
Feature added on 0.12.4
