### ISSUE TITLE
I'm an idiot.

### ISSUE THREAD

**Issue by Proxy14** [mysurvive/pf2e-thaum-vuln#8]
Forgive me, but I'm an absolute amateur when it comes to this stuff.  I downloaded the mod and have located the macro, but have no idea how to actually use it.

The actor has the Esoteric Lore correctly labeled under Lore Skills.  But whenever I try to use the macro, it tells me the actor does not have an item with the ID ayO61Cql4qSdvdGl. 

No idea what that means.

**Comment by mysurvive** [comment]
I'm guessing you're the GM? Do you have a thaumaturge selected? Can you hit f12 and expand the error message and send me the full trace?

**Comment by mysurvive** [comment]
Did you figure it out?

**Comment by mysurvive** [comment]
If you still need help, shoot me a message on Discord. MySurvive#1418
