### ISSUE TITLE
Modifiers don't apply when rolling the Recall Knowledge (Esoteric Lore) macro

### ISSUE THREAD

**Issue by SalamoneNahuel** [mysurvive/pf2e-thaum-vuln#86]
undry.js:68326 Unsupported modifier object (slug: int) passed
fetch @ foundry.js:68326
foundry.js:68326 Unsupported modifier object (slug: proficiency) passed
fetch @ foundry.js:68326
foundry.js:68326 Unsupported modifier object (slug: diverse-lore) passed
fetch @ foundry.js:68326
foundry.js:68326 Unsupported modifier object (slug: cha) passed
fetch @ foundry.js:68326

**Comment by mysurvive** [comment]
Something probably changed in an update. I'll look when I get a sec.
