### ISSUE TITLE
Typo on Personal Antithesis button

### ISSUE THREAD

**Issue by JulieWinchester** [mysurvive/pf2e-thaum-vuln#9]
Hi! Thanks very much for making this module. I just noticed a small typo on the Personal Antithesis button: https://github.com/mysurvive/pf2e-thaum-vuln/blob/e8f92d9d5fdde8bc8800a6f31cb85c107adbd61b/src/languages/en.json#L63

**Comment by mysurvive** [comment]
Whoops! I'll have this fixed with the next release.
