### ISSUE TITLE
Lingering Resistance automation

### ISSUE THREAD

**Issue by Karotteman** [mysurvive/pf2e-thaum-vuln#94]
Hi, with the adept benefit of the amulet unlocked, the lingering resistance effect doesn't applied, only the amulet's abeyance effect applied when I click on the button after damage roll. Is there is something I are missing ?

**Comment by mysurvive** [comment]
<img width="329" alt="image" src="https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/d7652086-2e59-4b70-bd11-9574036040b5">
It's applying for me. Can you provide some information on your workflow?

**Comment by mysurvive** [comment]
Are you using a different localization other than English? I have found the issue if so.
